version: '3.1'
services:
  postgres:
    container_name: my_postgres
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: credits
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: